# Generated by Django 3.0.3 on 2020-02-03 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('nickname', models.TextField()),
                ('alternate_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biological', models.BooleanField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webapp.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('married', models.BooleanField()),
                ('marriage_date', models.DateField()),
                ('divorced', models.BooleanField()),
                ('divorce_date', models.DateField()),
                ('notes', models.TextField()),
                ('current', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
                ('birth_location', models.TextField()),
                ('death_location', models.TextField()),
                ('living', models.BooleanField()),
                ('gender', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('occupations', models.TextField()),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.Name')),
                ('parents', models.ManyToManyField(to='webapp.Parent')),
                ('partnerships', models.ManyToManyField(to='webapp.Partnership')),
            ],
        ),
        migrations.AddField(
            model_name='partnership',
            name='children',
            field=models.ManyToManyField(related_name='_partnership_children_+', to='webapp.Person'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webapp.Person'),
        ),
    ]
