# Generated by Django 3.0.3 on 2020-02-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='partnerships',
        ),
        migrations.AddField(
            model_name='person',
            name='partnerships',
            field=models.ManyToManyField(to='webapp.Partnership'),
        ),
    ]
