# Generated by Django 3.0.3 on 2020-02-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200210_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_location',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_location',
            field=models.ManyToManyField(blank=True, related_name='birth_location', to='webapp.Location'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='death_location',
        ),
        migrations.AddField(
            model_name='person',
            name='death_location',
            field=models.ManyToManyField(blank=True, related_name='death_location', to='webapp.Location'),
        ),
    ]
