# Generated by Django 3.0.3 on 2020-02-11 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200210_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_location',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_location',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='birth_location', to='webapp.Location'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='person',
            name='death_location',
        ),
        migrations.AddField(
            model_name='person',
            name='death_location',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='death_location', to='webapp.Location'),
            preserve_default=False,
        ),
    ]
