# Generated by Django 3.0.3 on 2020-02-11 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200210_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='birth_location', to='webapp.Location'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='death_location', to='webapp.Location'),
        ),
        migrations.AlterField(
            model_name='person',
            name='partnerships',
            field=models.ManyToManyField(blank=True, to='webapp.Partnership'),
        ),
    ]
