# noinspection PyUnresolvedReferences
from gedcom.tags import *

# Header tags
GEDCOM_TAG_HEAD = 'HEAD'
GEDCOM_TAG_CHARSET = 'CHAR'
GEDCOM_TAG_GEDCOM = 'GEDC'
GEDCOM_TAG_VERSION = 'VERS'
GEDCOM_TAG_FORM = 'FORM'
GEDCOM_TAG_SUBMITTER = 'SUBM'
GEDCOM_TAG_CORP = 'CORP'

# Charsets
GEDCOM_CHARSET_ASCII = 'ASCII'
GEDCOM_CHARSET_UTF8 = 'UTF-8'

# Fields
GEDCOM_TAG_AGE = 'AGE'
GEDCOM_TAG_NAME_PREFIX = 'NPFX'
GEDCOM_TAG_NAME_SUFFIX = 'NSFX'
GEDCOM_TAG_SURNAME_PREFIX = 'SPFX'

# Events
GEDCOM_TAG_DIVORCE = 'DIV'
